### ISSUE TITLE
Tessellation errors

### ISSUE THREAD

**Issue by martin19** [tyt2y3/vaserenderer#6] opened 2020-03-01 15:50 UTC
Thanks for your effort to build this library. It seems to work for many cases. In the course of converting this to typescript/webgl (to be uploaded on github) I've discovered several cases where tesselation is wrong. I've appended the code that produces these errors along with screenshots of the actual tesselation. 

```C
void sample6()
{
	Vec2 points[5];
	points[0].x = 233; points[0].y = 199;
	points[1].x = 636; points[1].y = 547;
	points[2].x = 639; points[2].y = 547;
	points[3].x = 233; points[3].y = 571;
	points[4].x = 233; points[4].y = 199;	
	Color colors[5];
	colors[0].r = 1; colors[0].g = 0; colors[0].b = 0; colors[0].a = 1;
	colors[1].r = 1; colors[1].g = 0; colors[1].b = 0; colors[1].a = 1;
	colors[2].r = 1; colors[2].g = 0; colors[2].b = 0; colors[2].a = 1;
	colors[3].r = 1; colors[3].g = 0; colors[3].b = 0; colors[3].a = 1;
	colors[4].r = 1; colors[4].g = 0; colors[4].b = 0; colors[4].a = 1;
	double weights[5];
	weights[0] = 50;
	weights[1] = 50;
	weights[2] = 50;
	weights[3] = 50;
	weights[4] = 50;
	VASEr::VASErin::vertex_array_holder vah;
	VASEr::polyline_opt opt;
	VASEr::tessellator_opt topt;
	topt.parts = 0;
	topt.holder = &vah;
	topt.tessellate_only = 1;
	topt.triangulation = 1;
	opt.tess = &topt;
	opt.cap = VASEr::PLC_round;
	opt.joint = VASEr::PLJ_round;
	opt.feather = true;
	opt.feathering = 1.0;
	opt.no_feather_at_core = false;
	opt.no_feather_at_cap = false;

	VASEr::polyline(points, colors, weights, 5, &opt);
}
void sample7()
{
	Vec2 points[5];
	points[0].x = 233; points[0].y = 168;
	points[1].x = 614; points[1].y = 509;
	points[2].x = 614; points[2].y = 509;
	points[3].x = 100; points[3].y = 500;
	points[4].x = 233; points[4].y = 168;
	
	Color colors[5];
	colors[0].r = 1; colors[0].g = 0; colors[0].b = 0; colors[0].a = 1;
	colors[1].r = 1; colors[1].g = 0; colors[1].b = 0; colors[1].a = 1;
	colors[2].r = 1; colors[2].g = 0; colors[2].b = 0; colors[2].a = 1;
	colors[3].r = 1; colors[3].g = 0; colors[3].b = 0; colors[3].a = 1;
	colors[4].r = 1; colors[4].g = 0; colors[4].b = 0; colors[4].a = 1;
	double weights[5];
	weights[0] = 50;
	weights[1] = 50;
	weights[2] = 50;
	weights[3] = 50;
	weights[4] = 50;
	VASEr::VASErin::vertex_array_holder vah;
	VASEr::polyline_opt opt;
	VASEr::tessellator_opt topt;
	topt.parts = 0;
	topt.holder = &vah;
	topt.tessellate_only = 1;
	topt.triangulation = 1;
	opt.tess = &topt;
	opt.cap = VASEr::PLC_round;
	opt.joint = VASEr::PLJ_round;
	opt.feather = true;
	opt.feathering = 1.0;
	opt.no_feather_at_core = false;
	opt.no_feather_at_cap = false;

	VASEr::polyline(points, colors, weights, 5, &opt);
}
void sample8()
{
	Vec2 points[5];
	points[0].x = 177; points[0].y = 140;
	points[1].x = 501; points[1].y = 501;
	points[2].x = 500; points[2].y = 500;
	points[3].x = 100; points[3].y = 500;
	points[4].x = 177; points[4].y = 140;
	//  render([new Vector2(233, 199), new Vector2(636, 547), new Vector2(639, 547), new Vector2(233, 571)]);
	Color colors[5];
	colors[0].r = 1; colors[0].g = 0; colors[0].b = 0; colors[0].a = 1;
	colors[1].r = 1; colors[1].g = 0; colors[1].b = 0; colors[1].a = 1;
	colors[2].r = 1; colors[2].g = 0; colors[2].b = 0; colors[2].a = 1;
	colors[3].r = 1; colors[3].g = 0; colors[3].b = 0; colors[3].a = 1;
	colors[4].r = 1; colors[4].g = 0; colors[4].b = 0; colors[4].a = 1;
	double weights[5];
	weights[0] = 50;
	weights[1] = 50;
	weights[2] = 50;
	weights[3] = 50;
	weights[4] = 50;
	VASEr::VASErin::vertex_array_holder vah;
	VASEr::polyline_opt opt;
	VASEr::tessellator_opt topt;
	topt.parts = 0;
	topt.holder = &vah;
	topt.tessellate_only = 1;
	topt.triangulation = 1;
	opt.tess = &topt;
	opt.cap = VASEr::PLC_round;
	opt.joint = VASEr::PLJ_round;
	opt.feather = true;
	opt.feathering = 1.0;
	opt.no_feather_at_core = false;
	opt.no_feather_at_cap = false;

	VASEr::polyline(points, colors, weights, 5, &opt);
}
void sample9()
{
	Vec2 points[5];
	points[0].x = 177; points[0].y = 140;
	points[1].x = 497; points[1].y = 506;
	points[2].x = 500; points[2].y = 500;
	points[3].x = 100; points[3].y = 500;
	points[4].x = 177; points[4].y = 140;
	//  render([new Vector2(233, 199), new Vector2(636, 547), new Vector2(639, 547), new Vector2(233, 571)]);
	Color colors[5];
	colors[0].r = 1; colors[0].g = 0; colors[0].b = 0; colors[0].a = 1;
	colors[1].r = 1; colors[1].g = 0; colors[1].b = 0; colors[1].a = 1;
	colors[2].r = 1; colors[2].g = 0; colors[2].b = 0; colors[2].a = 1;
	colors[3].r = 1; colors[3].g = 0; colors[3].b = 0; colors[3].a = 1;
	colors[4].r = 1; colors[4].g = 0; colors[4].b = 0; colors[4].a = 1;
	double weights[5];
	weights[0] = 50;
	weights[1] = 50;
	weights[2] = 50;
	weights[3] = 50;
	weights[4] = 50;
	VASEr::VASErin::vertex_array_holder vah;
	VASEr::polyline_opt opt;
	VASEr::tessellator_opt topt;
	topt.parts = 0;
	topt.holder = &vah;
	topt.tessellate_only = 1;
	topt.triangulation = 1;
	opt.tess = &topt;
	opt.cap = VASEr::PLC_round;
	opt.joint = VASEr::PLJ_round;
	opt.feather = true;
	opt.feathering = 1.0;
	opt.no_feather_at_core = false;
	opt.no_feather_at_cap = false;

	VASEr::polyline(points, colors, weights, 5, &opt);
}
```

![image](https://user-images.githubusercontent.com/4746984/75628724-1dda4d00-5bdc-11ea-8966-e1baf5aafceb.png)
![image](https://user-images.githubusercontent.com/4746984/75628728-2b8fd280-5bdc-11ea-9c1a-d58407d225da.png)
![image](https://user-images.githubusercontent.com/4746984/75628745-47937400-5bdc-11ea-8d03-6f4e2de0dc0e.png)
![image](https://user-images.githubusercontent.com/4746984/75628753-6134bb80-5bdc-11ea-86a0-b969a9847a7b.png)

**Comment by martin19** [comment] 2020-03-01 17:03
NB: I'd be glad to help fixing these bugs, although I do not fully understand what's going on in the code. Best regards, Martin

**Comment by tyt2y3** [comment] 2020-03-01 17:13
Thank you for your report. I have started a reimplementation of this recently. Apart from bug fixes, it also take advantage of shaders. Would you mind testing this on https://github.com/tyt2y3/vaser-unity ?
It is implemented in C# and should be easier to port to Typescript.

**Comment by martin19** [comment] 2020-03-01 18:03
Hi, actually the typescript port based on C++ implementation is mostly done and I've discovered these bugs with it - but validated these are errors in the C++ implementation as well. Do you plan "backporting" fixes to the c++ implementation? I like the fact the tesselation is fairly independent and can be hooked to any triangle renderer.
I'd have to redo the port to typescript which took me some days, however if these bugs are fixed in the C# port it should be worth the effort for me. I'll let you know about my findings soon.

**Comment by martin19** [comment] 2020-03-01 20:16
Hi, 

I've tried the same examples in vaser-unity - these configurations seem to cause same errors here.

code and images below:
```C#
if(mode == 4) {
            polyline = new Polyline(
                new List<Vector2> {
                    new Vector2(233f/1000f, 199f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(636f/1000f, 547f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(639f/1000f, 547f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(233f/1000f, 571f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(233f/1000f, 199f/1000f) - new Vector2(0.5f,0.5f),
                },
                new List<Color> {
                    Color.red,
                    Color.red,
                    Color.red,
                    Color.red,
                    Color.red,
                },
                new List<float> {
                    50f/1000f, 50f/1000f, 50f/1000f, 50f/1000f, 50f/1000f
                },
                opt
            );
        } else if(mode == 5)
        {
            polyline = new Polyline(
                new List<Vector2> {
                    new Vector2(233f/1000f, 168f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(614f/1000f, 509f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(614f/1000f, 509f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(100f/1000f, 500f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(233f/1000f, 168f/1000f) - new Vector2(0.5f,0.5f),
                },
                new List<Color> {
                    Color.red,
                    Color.red,
                    Color.red,
                    Color.red,
                    Color.red,
                },
                new List<float> {
                    50f/1000f, 50f/1000f, 50f/1000f, 50f/1000f, 50f/1000f
                },
                opt
            );
        }
        else if (mode == 6) {
            polyline = new Polyline(
                new List<Vector2> {
                    new Vector2(177f/1000f, 140f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(501f/1000f, 501f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(500f/1000f, 500f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(100f/1000f, 500f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(177f/1000f, 140f/1000f) - new Vector2(0.5f,0.5f),
                },
                new List<Color> {
                    Color.red,
                    Color.red,
                    Color.red,
                    Color.red,
                    Color.red,
                },
                new List<float> {
                    50f/1000f, 50f/1000f, 50f/1000f, 50f/1000f, 50f/1000f
                },
                opt
            );
        } else if(mode == 7)
        {
            polyline = new Polyline(
               new List<Vector2> {
                    new Vector2(177f/1000f, 140f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(497f/1000f, 506f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(500f/1000f, 500f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(100f/1000f, 500f/1000f) - new Vector2(0.5f,0.5f),
                    new Vector2(177f/1000f, 140f/1000f) - new Vector2(0.5f,0.5f),
               },
               new List<Color> {
                    Color.red,
                    Color.red,
                    Color.red,
                    Color.red,
                    Color.red,
               },
               new List<float> {
                    50f/1000f, 50f/1000f, 50f/1000f, 50f/1000f, 50f/1000f
               },
               opt
           );
        }
```

![image](https://user-images.githubusercontent.com/4746984/75632950-3ad54700-5c01-11ea-9a65-4a18f29c33b3.png)
![image](https://user-images.githubusercontent.com/4746984/75632961-60625080-5c01-11ea-92a8-86ba5eed7666.png)
![image](https://user-images.githubusercontent.com/4746984/75632971-7c65f200-5c01-11ea-807c-714384de3c91.png)
![image](https://user-images.githubusercontent.com/4746984/75632991-969fd000-5c01-11ea-96d0-d4ed46fa4d50.png)

**Comment by tyt2y3** [comment] 2020-03-02 03:14
Thanks. I can reproduce the bug, and I'd able to fix it. Will get you posted.

**Comment by tyt2y3** [comment] 2020-03-02 09:25
I have briefly looked into it. Seems like the problems revolve around degeneration where "a segment's length is shorter than segment width". It's better for your app to filter such close points (aka clean the inputs). That say, I agree that these are "bug" cases, and I am trying to define the correct behavior for such cases.

**Comment by martin19** [comment] 2020-03-02 10:24
Thanks for the feedback! I think duplicate identical points should not change appearance while very short segments do - so I agree this cleanup can be considered a workaround which comes with loss in accuracy. As a general hint I'd say that these are probably very rare so I'd spent less time on making this optimal rather than making it work at all. Please let me know if I can help you with anything. I've thought about creating some more testcases to help increase robustness.

**Comment by tyt2y3** [comment] 2020-03-02 18:32
![image](https://user-images.githubusercontent.com/1782664/75705126-b57f8e80-5cf5-11ea-9bd5-1fbd020f446a.png)
The error case is the right most one. We can first flip the two points and we arrive at the middle case. Then we'd replace those with a single point on the intersection point of the two segments.
As for the left most case where the angle is obtuse, we can simply avoid joint processing.
I think this would solve those problems.

**Comment by martin19** [comment] 2020-03-02 23:37
Hi,
It seems browsers agree on these cases - left is chrome, right is firefox - edge is not shown but is identical. I think I think firefox uses cairo, chrome uses skia. They probably both tessellate. I could maybe hack something to visualize their tesselation algorithm. 

best regards, Martin

![image](https://user-images.githubusercontent.com/4746984/75727860-59613e00-5ce6-11ea-93c6-42d38df4c35f.png)

```
<svg  version="1.1" xmlns="http://www.w3.org/2000/svg" width="1000" height="1000">
    <g transform="translate(200,200)">
        <path d="M-110,100 0,10 0,-10 l110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,200)">
        <path d="M-110,100 0,10 0,-10 110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,200)">
        <path d="M-110,100 0,10 0,-10 110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:bevel" />
    </g>

    <!-- skeleton -->
    <g transform="translate(200,200)">
        <path d="M-110,100 0,10 0,-10 l110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,200)">
        <path d="M-110,100 0,10 0,-10 110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,200)">
        <path d="M-110,100 0,10 0,-10 110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:bevel" />
    </g>


    <g transform="translate(200,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:bevel" />
    </g>
    <!-- skeleton -->
    <g transform="translate(200,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:bevel" />
    </g>

    <g transform="translate(200,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:bevel" />
    </g>
    <!-- skeleton -->
    <g transform="translate(200,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:bevel" />
    </g>
</svg>
```

**Comment by martin19** [comment] 2020-03-02 23:41
Hi,
browsers seem to agree on this. Chrome on the left (skia), firefox on the right (cairo), and edge produce identical results. If it helps I could hack something to visualize how they tessellate.

best regards, Martin

![image](https://user-images.githubusercontent.com/4746984/75728209-71858d00-5ce7-11ea-98e7-1381cfe32ca9.png)

```xml
<svg  version="1.1" xmlns="http://www.w3.org/2000/svg" width="1000" height="1000">
    <g transform="translate(200,200)">
        <path d="M-110,100 0,10 0,-10 l110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,200)">
        <path d="M-110,100 0,10 0,-10 110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,200)">
        <path d="M-110,100 0,10 0,-10 110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:bevel" />
    </g>

    <!-- skeleton -->
    <g transform="translate(200,200)">
        <path d="M-110,100 0,10 0,-10 l110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,200)">
        <path d="M-110,100 0,10 0,-10 110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,200)">
        <path d="M-110,100 0,10 0,-10 110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:bevel" />
    </g>


    <g transform="translate(200,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:bevel" />
    </g>
    <!-- skeleton -->
    <g transform="translate(200,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,500)">
        <path d="M-110,100 0,10 0,-10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:bevel" />
    </g>

    <g transform="translate(200,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:gray;stroke-width:50;stroke-linejoin:bevel" />
    </g>
    <!-- skeleton -->
    <g transform="translate(200,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:miter" />
    </g>
    <g transform="translate(400,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:round" />
    </g>
    <g transform="translate(600,800)">
        <path d="M-110,100 0,-10 0,10 -110,-100" style="fill:none;stroke:black;stroke-width:1;stroke-linejoin:bevel" />
    </g>
</svg>
```

**Comment by tyt2y3** [comment] 2020-03-03 06:05
Thank you. I think I know what to do now.

**Comment by tyt2y3** [comment] 2020-03-03 16:44
![image](https://user-images.githubusercontent.com/1782664/75797742-8bd76d80-5db0-11ea-8a5f-7505dabc9eb4.png)
I have seemingly fixed 4~6 in https://github.com/tyt2y3/vaser-unity/commit/72270564b54ec443ec4780c8b7fe4a9ea77adb85
Luckily the code addition is not much. Can you test a bit and backport to this repo and create a pull request if you'd think that is good?

**Comment by martin19** [comment] 2020-03-03 22:07
Hi, I think you're right - case 4 above is fixed. 

I guess there is some more work to do to make the algorithm stable for many edge cases that can arise. see this test video: https://imgur.com/jl8GVxr
I know this video must seem like "putting the finger in the wound" - but in my use cases edgecases will arise sooner or later.

**Comment by tyt2y3** [comment] 2020-03-04 00:33
Yes because that is case 7 I haven’t fixed yet.
No need to be sorry I have done such things before.
Can I know more about your use case and the app?
Again you should consider clean up the input more than relying on the renderer.
The HTML demo seemed promising.
Will it be open source some day?
That sure is a nice addition to the family ;)
Other than this bug, can you also review is there other bugs you fixed during the process and create a PR also?
Finally, the approach I used in vaser-unity is different, it uses shaders for feathering so that is less triangles and more efficient. If performance is what you’re after, consider adopting that. And may be wasm too.

**Comment by martin19** [comment] 2020-03-04 20:39
Hi,
the app I'm working on is an image editor with vector editing capabilities. Primary focus for vector editing lies on quality of the drawing, performance comes second. I'll try cleaning up the input data, however I think I'll need also boundary cases working accurately before it will be usable for me. 

I've uploaded the vaser port to github: https://github.com/martin19/vaser-ts
Please let me know if there is anything wrong with the short license - or if you want anything else to be said there.

Apart from your bugfix I have not fixed anything else yet - there were some bugs introduced during porting which I think I have fixed. I've done some performance tests tessellating with vaser and despite the complexity of the algorithm it performs good enough in plain javascript.

**Comment by tyt2y3** [comment] 2021-04-30 04:51
Closing this and redirect people to https://github.com/tyt2y3/vaser-unity

**Closed as completed by tyt2y3** 2021-04-30 04:52 UTC
